import asyncHandler from "express-async-handler";
import { Customer } from "../models/customerModel.js";
import { User } from "../models/userModel.js";
import {
  getAutoGeneratedId,
  getDocId,
  getProductFields,
} from "../utils/docIds.js";
import { RentOrder } from "../models/rentOrderModel.js";
import { RentItem } from "../models/rentItemModel.js";
import { Transaction } from "../models/transactionModel.js";
import { sendSMS } from "../notificationSMS/smsNotification.js";
import { addOrFetchCustomer } from "../utils/customer.js";
import { addOrEditTransaction } from "../utils/transaction.js";
import { updateDailySummary } from "../utils/updateDailySummary.js";
import { getPopulatedRentOrders } from "../services/rentOrderService.js";
import { deleteRentOrder } from "../utils/rentOrder.js";

export const createRentOrder = asyncHandler(async (req, res) => {
  const { store } = req.query;

  const {
    customer: { name, mobile },
    rentDate,
    returnDate,
    salesPerson,
    rentOrderDetails,
    totalPrice,
    subTotal,
    paymentType,
    linkedSalesOrderId,
  } = req.body;

  // Check for required fields
  if (
    !mobile ||
    !name ||
    !rentDate ||
    !returnDate ||
    !salesPerson ||
    !rentOrderDetails.length > 0 ||
    !paymentType
  ) {
    res.status(400);
    throw new Error("Required fields are not provided.");
  }
  //   let customer = undefined;
  //   customer = await Customer.findOne({ mobile }).lean().exec();
  //   if (!customer) {
  //     customer = await Customer.create({ name, mobile });
  //   }

  const customer = await addOrFetchCustomer({ name, mobile });

  const salesPersonDoc = await User.findOne({ userId: salesPerson })
    .lean()
    .exec();
  if (!salesPersonDoc) {
    res.status(404);
    throw new Error(`No user found for ID ${salesPerson}`);
  }

  // Loop through each order and populate rentOrderDetails with rentItem status
  const updatedRentOrderDetails = rentOrderDetails.map((detail) => ({
    ...detail,
    status: "Rented",
  }));

  const orderData = {
    ...req.body,
    rentOrderDetails: updatedRentOrderDetails,
    customer: customer.customerId,
    salesPerson: salesPerson,
    store,
  };

  const newOrder = await RentOrder.create(orderData);

  if (!newOrder) {
    res.status(500);
    throw new Error("Error creating rent order.");
  }

  if (!linkedSalesOrderId) {
    // Create a credit transaction
    const transactionData = {
      transactionType: "Income",
      transactionCategory: "Rent Order",
      paymentType: paymentType,
      isInitialTransaction: true,
      salesPerson: salesPerson,
      store,
      amount: newOrder.advPayment,
      description: `Rent Order: ${newOrder.rentOrderId}`,
    };

    // only add the transaction if not linked to a sales order because sales order already has the transaction.
    await addOrEditTransaction(transactionData);
  }

  // Update the status of each rent item in the order to 'Not Returned'
  for (const detail of rentOrderDetails) {
    await RentItem.findOneAndUpdate(
      { rentItemId: detail.rentItemId },
      { status: "Rented" }
    );
  }

  // Send SMS and handle the result
  const messageBody = `Hi ${name}. Your Order Id is ${newOrder.rentOrderId} Order total is ${subTotal}. Your order balance is ${newOrder?.balance}. Thank you come again.`;
  const smsResult = await sendSMS(messageBody, mobile);

  let smsStatus = "Success";
  if (!smsResult.success) {
    smsStatus = "Failed";
    console.error("SMS sending failed:", smsResult.error);
  }

  res.json({
    message: "New rent order created successfully.",
    success: true,
    data: newOrder,
    smsStatus,
  });
});

export const updateRentOrder = asyncHandler(async (req, res) => {
  const { rentOrderId } = req.params;

  const { store } = req.query

  const {
    customer: { name, mobile },
    salesPerson,
    rentOrderDetails,
    paymentType,
    linkedSalesOrderId,
    advPayment,
  } = req.body;

  if (!rentOrderId) {
    throw new Error("rentOrderId is not provided!");
  }

  const rentOrder = await RentOrder.findOne({ rentOrderId }).lean().exec();

  if (!rentOrder) {
    throw new Error("No rent order Found!");
  }

  const customer = await addOrFetchCustomer({ name, mobile });

  const salesPersonDoc = await User.findOne({ userId: salesPerson })
    .lean()
    .exec();
  if (!salesPersonDoc) {
    throw new Error(`No user found for ID ${salesPerson}`);
  }

  // delete if no rent order details
  if (rentOrderDetails.length === 0) {
    const deletedRentOrder = await RentOrder.findOneAndDelete({ rentOrderId });

    if (!deletedRentOrder) {
      throw new Error(`Rent Order with ID ${rentOrderId} not found.`);
    }

    res.json({
      message: "Rent Order deleted successfully.",
      success: true,
    });
  }

  const updatedRentOrderDetails = rentOrderDetails.map((detail) => ({
    ...detail,
    status: "Rented",
  }));

  const updateData = {
    ...req.body,
    rentOrderDetails: updatedRentOrderDetails,
    customer: customer.customerId,
    salesPerson: salesPerson,
  };

  const rentItemsInOrder = rentOrder.rentOrderDetails.map(
    (detail) => detail.rentItemId
  );

  // find the items newly added to the order and change the status to rented
  const newlyAddedItems = rentOrderDetails.filter(
    (detail) =>
      !rentItemsInOrder.some((rentItemId) => rentItemId === detail.rentItemId)
  );

  for (const detail of newlyAddedItems) {
    await RentItem.findOneAndUpdate(
      {
        rentItemId: detail.rentItemId,
      },
      {
        status: "Rented",
      }
    );
  }
  // find the removed items from the order and change the status to available

  const rentItemsInTheUpdatedOrder = rentOrderDetails.map(
    (detail) => detail.rentItemId
  );

  const removedRentItems = rentItemsInOrder.filter(
    (item) =>
      !rentItemsInTheUpdatedOrder.some((rentItemId) => rentItemId === item)
  );

  for (const item of removedRentItems) {
    await RentItem.findOneAndUpdate(
      {
        rentItemId: item,
      },
      {
        status: "Available",
      }
    );
  }

  const updatedRentOrder = await RentOrder.findOneAndUpdate(
    { rentOrderId },
    { ...updateData },
    { new: true }
  );

  if (!updatedRentOrder) {
    throw new Error(`Rent Order with ID ${rentOrderId} not found.`);
  }

  if (!linkedSalesOrderId) {
    // Create a credit transaction
    const transactionData = {
      transactionType: "Income",
      transactionCategory: "Rent Order",
      paymentType: paymentType,
      isInitialTransaction: true,
      salesPerson: salesPerson,
      store,
      amount: updatedRentOrder.advPayment,
      description: `Rent Order: ${updatedRentOrder.rentOrderId}`,
    };

    // only add the transaction if not linked to a sales order because sales order already has the transaction.
    await addOrEditTransaction(transactionData);
  }
  // Create a credit transaction

  res.json({
    message: "Rent Order updated successfully.",
    success: true,
    data: updatedRentOrder,
  });
});

// @desc    Get all orders
// @route   GET /api/orders
// @access  Public
export const getAllRentOrders = asyncHandler(async (req, res) => {
  const { store, rentDate, isNewRentOut } = req.query;

  // Initialize filter object
  const filter = { store };

  // Add `rentDate` filter if provided
  if (rentDate) {
    const date = new Date(rentDate);
    const startOfDay = new Date(date.setHours(0, 0, 0, 0));
    const endOfDay = new Date(date.setHours(23, 59, 59, 999));
    filter.rentDate = { $gte: startOfDay, $lte: endOfDay };
  }

  // Add `isNewRentOut` filter if provided
  if (isNewRentOut !== undefined) {
    filter.isNewRentOut = isNewRentOut === "true"; // Convert to boolean
  }

  const orders = await getPopulatedRentOrders({ filter });

  if (!orders) {
    throw new Error("no orders found!");
  }

  res.json({
    message: "All Orders Fetched Successfully.",
    success: true,
    data: orders,
  });
});

export const getSingleRentOrder = asyncHandler(async (req, res) => {
  const { rentOrderId } = req?.params;

  const filter = { rentOrderId };

  const rentOrder = await getPopulatedRentOrders({ filter });
  //   const rentOrder = await RentOrder.findOne({ rentOrderId })
  //     .select("-_id -__v")
  //     .populate({
  //       path: "customer",
  //       select: "-_id -createdAt -updatedAt -__v",
  //     })
  //     .populate(
  //       "salesPerson",
  //       "-createdAt -updatedAt -password -_id -__v -refreshToken"
  //     )
  //     .lean();

  if (!rentOrder) {
    throw new Error("no orders found!");
  }
  res.json({
    message: "Rent Order Fetched Successfully!",
    success: true,
    data: rentOrder,
  });
});
export const deleteRentOrders = asyncHandler(async (req, res) => {
  const { rentOrderId } = req?.params;

  const deletedRentOrder = await deleteRentOrder(rentOrderId);

  if (!deletedRentOrder) {
    throw new Error("Rent order deletion failed!");
  }

  res.json({
    message: "Rent Order Deleted Successfully!",
    success: true,
  });
});

export const searchSingleOrder = asyncHandler(async (req, res) => {
  const { rentItemId } = req.params;

  if (!rentItemId) {
    throw new Error("Rent order Id not found");
  }

  const filter = {
    "rentOrderDetails.rentItemId": rentItemId,
    orderStatus: { $ne: "Completed" },
  }

//   const rentOrder = await RentOrder.findOne()
//     .select("-_id -__v")
//     .populate({
//       path: "customer",
//       select: "-_id -createdAt -updatedAt -__v",
//     })
//     .populate(
//       "salesPerson",
//       "-createdAt -updatedAt -password -_id -__v -refreshToken"
//     )
//     .lean();

  const rentOrder = await getPopulatedRentOrders({filter})

  if (!rentOrder || !rentOrder.length > 0) {
    throw new Error("No orders found!");
  }

  //   for (let detail of rentOrder.rentOrderDetails) {
  //     const rentItem = await RentItem.findOne({ rentItemId: detail.rentItemId })
  //       .select("status")
  //       .lean();

  //     if (rentItem) {
  //       detail.status = rentItem.status;
  //     } else {
  //       detail.status = "Unknown"; // Handle cases where rent item might not be found
  //     }
  //   }

  res.json({
    message: "Rent Order and related rent items found successfully!",
    success: true,
    data: rentOrder[0],
  });
});

export const rentReturn = asyncHandler(async (req, res) => {
  const { rentItemId } = req.params;

  // Find the rent order by rentOrderId
  const rentItem = await RentItem.findOne({ rentItemId });

  if (!rentItem) {
    res.status(404);
    throw new Error(`No rent Item found with ID ${rentItemId}`);
  }

  // Update the status of each rent item in the order to 'Available'
  rentItem.status = "Available";

  await rentItem.save();

  // Find the rent order that includes this rent item
  const rentOrder = await RentOrder.find({
    "rentOrderDetails.rentItemId": rentItemId,
    "rentOrderDetails.status": "Rented",
  });

  if (!rentOrder.length > 0) {
    res.status(404);
    throw new Error(`No rent order found for rent item ID ${rentItemId}`);
  }

  for (let order of rentOrder) {
    // [Todo- remove this after the previous orders are updated.]
    for (let detail of order.rentOrderDetails) {
      if (detail.rentItemId === rentItemId) {
        detail.status = "Available";
      }
      // const rentItem = await RentItem.findOne({ rentItemId: detail.rentItemId })
      //   .select("status")
      //   .lean();

      // if (rentItem) {
      //   detail.status = rentItem.status;
      // } else {
      //   detail.status = "Unknown"; // Handle cases where rent item might not be found
      // }
    }

    await order.save();

    rentItem.itemHistory.push({ rentOrderId: order.rentOrderId });

    await rentItem.save();

    // Check if all items in the rent order have status 'Available'
    const allItemsReturned = order.rentOrderDetails.every(
      (item) =>
        item.rentItemId === rentItemId || // Include the updated item
        item.status === "Available"
    );

    // If all items are available, mark the rent order as 'Completed'
    if (allItemsReturned) {
      order.orderStatus = "Completed";
      await order.save();
    }
  }

  res.json({
    message: `Rent return successful!`,
    success: true,
  });
});
