import asyncHandler from "express-async-handler";
import { Customer } from "../models/customerModel.js";
import { User } from "../models/userModel.js";
import {
  getAutoGeneratedId,
  getDocId,
  getProductFields,
} from "../utils/docIds.js";
import { RentOrder } from "../models/rentOrderModel.js";
import { RentItem } from "../models/rentItemModel.js";
import { Transaction } from "../models/transactionModel.js";
import { sendSMS } from "../notificationSMS/smsNotification.js";

export const createOrder = asyncHandler(async (req, res) => {
  const { store } = req.query;

  const {
    customer: { name, mobile },
    rentDate,
    returnDate,
    salesPerson,
    rentOrderDetails,
    totalPrice,
    subTotal,
    paymentType,
  } = req.body;

  // Check for required fields
  if (
    !mobile ||
    !name ||
    !rentDate ||
    !returnDate ||
    !salesPerson ||
    !rentOrderDetails ||
    !totalPrice ||
    !subTotal ||
    !paymentType
  ) {
    res.status(400);
    throw new Error("Required fields are not provided.");
  }
  let customer = undefined;
  customer = await Customer.findOne({ mobile }).lean().exec();
  if (!customer) {
    customer = await Customer.create({ name, mobile });
  }

  const salesPersonDoc = await User.findOne({ userId: salesPerson })
    .lean()
    .exec();
  if (!salesPersonDoc) {
    res.status(404);
    throw new Error(`No user found for ID ${salesPerson}`);
  }

  // Loop through each order and populate rentOrderDetails with rentItem status

const updatedRentOrderDetails = rentOrderDetails.map((detail)=> ({
    ...detail, status: 'Rented'
}))

  const orderData = {
    ...req.body,
    rentOrderDetails: updatedRentOrderDetails,
    customer: customer._id,
    salesPerson: salesPersonDoc._id,
    store,
  };

  const newOrder = await RentOrder.create(orderData);

  // Create a credit transaction
  const newTransaction = await Transaction.create({
    transactionType: "Income",
    transactionCategory: "Rent Order",
    paymentType: paymentType,
    isInitialTransaction: true,
    salesPerson: salesPersonDoc.name,
    store,
    date: new Date(),
    amount: newOrder.advPayment,
    description: `Rent Order: ${newOrder.rentOrderId}`,
  });

  const messageBody = `Hi ${name}. Your Order Id is ${newOrder.rentOrderId}. Your order balance is ${newOrder?.balance}. Thank you come again.`;
  await sendSMS(messageBody, mobile);

  // Update the status of each rent item in the order to 'Not Returned'
  for (const detail of rentOrderDetails) {
    await RentItem.findOneAndUpdate(
      { rentItemId: detail.rentItemId },
      { status: "Rented" }
    );
  }

  res.json({
    message: "New rent order created successfully.",
    success: true,
    data: newOrder,
  });
});

// @desc    Get all orders
// @route   GET /api/orders
// @access  Public
export const getAllOrders = asyncHandler(async (req, res) => {
  const { store } = req.query;

  const orders = await RentOrder.find({ store })
    .select("-_id -__v")
    .populate({
      path: "customer",
      select: "-_id -createdAt -updatedAt -__v",
    })
    .populate(
      "salesPerson",
      "-createdAt -updatedAt -password -_id -__v -refreshToken"
    )
    .lean();

  if (!orders) {
    throw new Error("no orders found!");
  }

//   // Loop through each order and populate rentOrderDetails with rentItem status
//   for (let order of orders) {
//     for (let detail of order.rentOrderDetails) {
//       const rentItem = await RentItem.findOne({ rentItemId: detail.rentItemId })
//         .select("status")
//         .lean();

//       if (rentItem) {
//         detail.status = rentItem.status;
//       } else {
//         detail.status = "Unknown"; // Handle cases where rent item might not be found
//       }
//     }
//   }

  // Sort orders by extracting the numeric part of salesOrderId
  const sortedOrders = orders.sort((a, b) => {
    const aId = parseInt(a.rentOrderId.replace(/\D/g, ""), 10);
    const bId = parseInt(b.rentOrderId.replace(/\D/g, ""), 10);
    return bId - aId;
  });

  res.json({
    message: "All Orders Fetched Successfully.",
    success: true,
    data: sortedOrders,
  });
});

export const getSingleRentOrder = asyncHandler(async (req, res) => {
  const { rentOrderId } = req?.params;
  const rentOrder = await RentOrder.findOne({ rentOrderId })
    .select("-_id -__v")
    .populate({
      path: "customer",
      select: "-_id -createdAt -updatedAt -__v",
    })
    .populate(
      "salesPerson",
      "-createdAt -updatedAt -password -_id -__v -refreshToken"
    )
    .lean();

  if (!rentOrder) {
    throw new Error("no orders found!");
  }
  res.json({
    message: "Rent Order Fetched Successfully!",
    success: true,
    data: rentOrder,
  });
});

export const searchSingleOrder = asyncHandler(async (req, res) => {
  const { rentItemId } = req.params;

  if (!rentItemId) {
    throw new Error("Rent order Id not found");
  }

  const rentOrder = await RentOrder.findOne({
    "rentOrderDetails.rentItemId": rentItemId,
    orderStatus: { $ne: "Completed" },
  })
    .select("-_id -__v")
    .populate({
      path: "customer",
      select: "-_id -createdAt -updatedAt -__v",
    })
    .populate(
      "salesPerson",
      "-createdAt -updatedAt -password -_id -__v -refreshToken"
    )
    .lean();

  if (!rentOrder) {
    throw new Error("No orders found!");
  }

//   for (let detail of rentOrder.rentOrderDetails) {
//     const rentItem = await RentItem.findOne({ rentItemId: detail.rentItemId })
//       .select("status")
//       .lean();

//     if (rentItem) {
//       detail.status = rentItem.status;
//     } else {
//       detail.status = "Unknown"; // Handle cases where rent item might not be found
//     }
//   }

  res.json({
    message: "Rent Order and related rent items found successfully!",
    success: true,
    data: rentOrder,
  });
});

export const rentReturn = asyncHandler(async (req, res) => {
  const { rentItemId } = req.params;

  // Find the rent order by rentOrderId
  const rentItem = await RentItem.findOne({ rentItemId });

  if (!rentItem) {
    res.status(404);
    throw new Error(`No rent Item found with ID ${rentItemId}`);
  }

  // Update the status of each rent item in the order to 'Available'
  rentItem.status = "Available";

  await rentItem.save();

  // Find the rent order that includes this rent item
  const rentOrder = await RentOrder.findOne({
    "rentOrderDetails.rentItemId": rentItemId,
  });

  if (!rentOrder) {
    res.status(404);
    throw new Error(`No rent order found for rent item ID ${rentItemId}`);
  }

  for (let detail of rentOrder.rentOrderDetails) {
    if (detail.rentItemId === rentItemId) {
        detail.status = 'Available'
    }
    // const rentItem = await RentItem.findOne({ rentItemId: detail.rentItemId })
    //   .select("status")
    //   .lean();

    // if (rentItem) {
    //   detail.status = rentItem.status;
    // } else {
    //   detail.status = "Unknown"; // Handle cases where rent item might not be found
    // }
  }

  // Check if all items in the rent order have status 'Available'
  const allItemsReturned = rentOrder.rentOrderDetails.every(
    (item) =>
      item.rentItemId === rentItemId || // Include the updated item
      item.status === "Available"
  );

  // If all items are available, mark the rent order as 'Completed'
  if (allItemsReturned) {
    rentOrder.orderStatus = "Completed";
    await rentOrder.save();
  }

  res.json({
    message: `Rent return successful!`,
    success: true,
  });
});

export const updateOrder = asyncHandler(async (req, res) => {
  const { rentOrderId } = req.params;

  const {
    customer: { name, mobile },
    salesPerson,
    rentOrderDetails,
    paymentType,
    advPayment
  } = req.body;

  if (!rentOrderId) {
    throw new Error("rentOrderId is not provided!");
  }

  const rentOrder = await RentOrder.findOne({ rentOrderId }).lean().exec();

  if (!rentOrder) {
    throw new Error("No rent order Found!");
  }
  let customer = undefined;
  customer = await Customer.findOne({ mobile }).lean().exec();
  if (!customer) {
    customer = await Customer.create({ name, mobile });
  }
  const salesPersonDoc = await getDocId(User, "userId", salesPerson);

  const updatedRentOrderDetails = rentOrderDetails.map((detail)=> ({
    ...detail, status: 'Rented'
}))


  const updateData = {
    ...req.body,
    rentOrderDetails: updatedRentOrderDetails,
    customer: customer._id,
    salesPerson: salesPersonDoc,
  };

  const updatedOrder = await RentOrder.findByIdAndUpdate(
    rentOrder._id,
    { ...updateData },
    { new: true }
  )
    .populate({
      path: "customer",
      select: "-_id -createdAt -updatedAt -__v",
    })
    .populate(
      "salesPerson",
      "-createdAt -updatedAt -password -_id -__v -refreshToken"
    )
    .lean();

  if (!updatedOrder) {
    res.status(404);
    throw new Error(`RentOrder with ID ${orderId} not found.`);
  }

  // Create a credit transaction
  const newTransaction = await Transaction.findOneAndUpdate(
    { description: `Rent Order: ${rentOrderId}`, isInitialTransaction: true },
    {
      paymentType: paymentType,
      amount: advPayment,
    }
  );

  // Update the status of each rent item in the order to 'Not Returned'
  for (const detail of rentOrder.rentOrderDetails) {
    await RentItem.findOneAndUpdate(
      { rentItemId: detail.rentItemId },
      { status: "Rented" }
    );
  }

  res.json({
    message: "Rent Order updated successfully.",
    success: true,
    data: updatedOrder,
  });
});
