import asyncHandler from "express-async-handler";
import { Customer } from "../models/customerModel.js";
import { SalesOrder } from "../models/salesOrderModel.js";
import { Product } from "../models/productModel.js";
import { User } from "../models/userModel.js";
import {
  getAutoGeneratedId,
  getDocId,
  getProductFields,
} from "../utils/docIds.js";
import { Material } from "../models/materialModel.js";
import { Transaction } from "../models/transactionModel.js";
import { updateDailySummary } from "../utils/updateDailySummary.js";
import { RentOrder } from "../models/rentOrderModel.js";
import { sendSMS } from "../notificationSMS/smsNotification.js";
import { RentItem } from "../models/rentItemModel.js";
import { addOrFetchCustomer } from "../utils/customer.js";
import { addOrEditTransaction } from "../utils/transaction.js";
import { getPopulatedSalesOrders } from "../services/salesOrderService.js";
import { deleteRentOrder } from "../utils/rentOrder.js";

export const createOrder = asyncHandler(async (req, res) => {
  const { store } = req.query;

  const {
    customer: { name, mobile },
    orderDate,
    deliveryDate,
    salesPerson,
  } = req.body;

  // Check for required fields
  if (!mobile || !name || !orderDate || !deliveryDate || !salesPerson) {
    res.status(400);
    throw new Error("Required fields are not provided.");
  }
  const customer = await addOrFetchCustomer({ name, mobile });

  const salesPersonDoc = await User.findOne({ userId: salesPerson })
    .lean()
    .exec();

  if (!salesPersonDoc) {
    throw new Error("No sales person found");
  }

  const orderData = {
    ...req.body,
    store,
    customer: customer.customerId,
    salesPerson: salesPerson,
    orderDetails: [],
    totalPrice: 0,
    subTotal: 0,
    discount: 0,
    advPayment: 0,
    balance: 0,
  };

  const newOrder = await SalesOrder.create(orderData);

  // // Send SMS and handle the result
  // const messageBody = `Hi ${name}. Your Order Id is ${newOrder.salesOrderId} and OrderTotal is ${subTotal}. Your order balance is ${newOrder?.balance}. Thank you, come again.`;
  // const smsResult = await sendSMS(messageBody, mobile);

  // let smsStatus = "Success";
  // if (!smsResult.success) {
  //   smsStatus = "Failed";
  //   console.error("SMS sending failed:", smsResult.error);
  // }

  res.json({
    message: "New order created successfully.",
    success: true,
    data: { ...newOrder.toObject(), customer },
  });
});

export const updateSalesOrder = asyncHandler(async (req, res) => {
  const {
    customer: { name, mobile },
    orderDate,
    deliveryDate,
    salesPerson,
    orderDetails,
    totalPrice,
    subTotal,
    paymentType,
    advPayment,
  } = req.body;

  const { salesOrderId } = req?.params;
  const { store } = req.query;

  if (!salesOrderId) {
    throw new Error("OrderId is not provided!");
  }

  const salesOrder = await SalesOrder.findOne({ salesOrderId }).lean().exec();
  if (!salesOrder) {
    throw new Error(`No sales order found with ID: ${salesOrderId}`);
  }

  const salesPersonRecord = await User.findOne({ userId: salesPerson })
    .lean()
    .exec();

  if (!salesPersonRecord) {
    throw new Error("No sales person found");
  }

  let customer = addOrFetchCustomer({ name, mobile });

  const orderData = {
    ...req.body,
    customer: customer.customerId,
    salesPerson,
    orderDetails,
  };

  const updateOrder = await SalesOrder.findByIdAndUpdate(
    salesOrder._id,
    {
      ...orderData,
    },
    {
      new: true,
    }
  );

  // Send SMS and handle the result
  const messageBody = `Hi ${name}. Your Order Id is ${updateOrder.salesOrderId} and OrderTotal is ${subTotal}. Your order balance is ${updateOrder?.balance}. Thank you, come again.`;
  const smsResult = await sendSMS(messageBody, mobile);

  let smsStatus = "Success";
  if (!smsResult.success) {
    smsStatus = "Failed";
    console.error("SMS sending failed:", smsResult.error);
  }

  const transactionData = {
    description: `Sales Order: ${salesOrder.salesOrderId}`,
    transactionType: "Income",
    transactionCategory: "Sales Order",
    paymentType: paymentType,
    salesPerson: salesPerson,
    store,
    isInitialTransaction: true,
    amount: advPayment,
  };

  const transaction = await addOrEditTransaction(transactionData);

  await updateDailySummary(transaction);

  res.json({
    message: "Sales order updated successfully.",
    success: true,
    data: updateOrder,
    smsStatus
  });
});

// @desc    Get all orders
// @route   GET /api/orders
// @access  Public
export const getAllOrders = asyncHandler(async (req, res) => {
  const { store } = req.query;

  const filter = { store };

  const salesOrders = await getPopulatedSalesOrders({ filter });

  res.json({
    message: "All Orders Fetched Successfully.",
    success: true,
    data: salesOrders,
  });
});

export const getSingleSalesOrder = asyncHandler(async (req, res) => {
  const { salesOrderId } = req?.params;

  const filter = { salesOrderId };

  const salesOrder = await getPopulatedSalesOrders({ filter });

  if (!salesOrder) {
    throw new Error("No sales order found!");
  }

  res.json({
    message: "Sales Order Fetched Successfully.",
    success: true,
    data: salesOrder,
  });
});

// export const cancelSalesOrder = asyncHandler(async (req, res) => {
//   const { salesOrderId } = req?.params;

//   const salesOrder = await SalesOrder.findOneAndDelete({ salesOrderId });

//   if (!salesOrder) {
//     throw new Error("Sales order Cancellation Failed!");
//   }

//   //   for (const detail of salesOrder.orderDetails) {
//   //     for (const rentItem of detail.rentItems) {
//   //       await RentItem.findOneAndUpdate(
//   //         { rentItemId: rentItem.rentItemId },
//   //         { status: "Available" }
//   //       );
//   //     }
//   //   }

//   res.json({
//     message: "Sales Order Cancelled Successfully.",
//     success: true,
//   });
// });

export const deleteSalesOrder = asyncHandler(async (req, res) => {
  const { salesOrderId } = req?.params;

  const salesOrder = await SalesOrder.findOne({ salesOrderId }).lean().exec();

  if (!salesOrder) {
    throw new Error("No sales order found!");
  }

  // delete linked rentOrder
  if (salesOrder.linkedRentOrder) {
    const rentOrder = await RentOrder.findOne({
      rentOrderId: salesOrder.linkedRentOrder,
    }).lean();
    if (rentOrder) {
      const deletedRentOrder = await deleteRentOrder(
        salesOrder.linkedRentOrder
      );
      if (!deletedRentOrder) {
        throw new Error("Rent order deletion failed!");
      }
    }
  }

  const deletedSalesOrder = await SalesOrder.findOneAndDelete({ salesOrderId });

  if (!deletedSalesOrder) {
    throw new Error("Sales order Deletion Failed!");
  }

  res.json({
    message: "Sales Order Deleted Successfully.",
    success: true,
  });
});

export const getSalesOrderOrRentOrderForPayment = asyncHandler(
  async (req, res) => {
    const { orderId } = req.params;
    let order = null;
    let transactions = [];

    // Determine if it's a Sales Order or Rent Order based on prefix (e.g., "RW" or "KE")

    // Check in SalesOrder collection
    order = await SalesOrder.findOne({ salesOrderId: orderId })
      .populate("customer", "name mobile")
      .lean()
      .exec();

    // If no Sales Order found, check in RentOrder collection
    if (!order) {
      order = await RentOrder.findOne({ rentOrderId: orderId })
        .populate("customer", "name mobile")
        .lean()
        .exec();
    }

    // If no order found, return an error
    if (!order) {
      res.status(404);
      throw new Error(`No order found with ID: ${orderId}`);
    }

    // Find related transactions based on the orderId in the description
    transactions = await Transaction.find({
      description: new RegExp(orderId, "i"), // Search transactions that contain orderId in the description
    })
      .lean()
      .exec();

    const sortedTransactions = transactions.sort(
      (a, b) => new Date(b.date) - new Date(a.date)
    );

    // Return the order details and transactions
    res.json({
      message: `order fetched successfully.`,
      success: true,
      data: {
        order,
        transactions: sortedTransactions,
      },
    });
  }
);

export const updateSalesOrRentOrder = asyncHandler(async (req, res) => {
  const { orderId } = req.params;
  const { paymentAmount, paymentType } = req.body;

  // Validate input
  if (!paymentAmount || !paymentType) {
    res.status(400);
    throw new Error("Payment amount and payment type are required.");
  }

  let order = null;
  let orderType = "";
  let balance = 0;

  // Check if it's a Sales Order or Rent Order based on the orderId prefix
  if (orderId.startsWith("RW") || orderId.startsWith("KE")) {
    // Check in SalesOrder
    order = await SalesOrder.findOne({ salesOrderId: orderId })
      .populate({
        path: "customer",
        select: "-_id -createdAt -updatedAt -__v",
      })
      .exec();
    orderType = "Sales Order";
  }

  if (!order) {
    // If no SalesOrder is found, check in RentOrder
    order = await RentOrder.findOne({ rentOrderId: orderId })
      .populate({
        path: "customer",
        select: "-_id -createdAt -updatedAt -__v",
      })
      .exec();
    orderType = "Rent Order";
  }

  if (!order) {
    res.status(404);
    throw new Error(`Order not found with ID: ${orderId}`);
  }

  // Calculate the new balance
  const updatedAdvPayment = (order.advPayment || 0) + Number(paymentAmount);
  balance = order.totalPrice - updatedAdvPayment;

  // Update the order with the new payment and balance
  order.advPayment = updatedAdvPayment;
  order.balance = balance;
  order.paymentType = paymentType;

  // Save the updated order
  const updatedOrder = await order.save();

  // Create a new transaction
  const newTransaction = await Transaction.create({
    transactionType: "Income",
    transactionCategory: orderType,
    paymentType: paymentType,
    salesPerson: order.salesPerson, // Assuming this is already populated with user info
    store: order.store,
    amount: paymentAmount,
    description: `${orderType}: ${orderId}`, // Include orderId in the transaction description
  });

  const messageBody = `Hi ${order.customer.name}. Your order balance is ${order?.balance}. Thank you come again.`;
  await sendSMS(messageBody, order.customer.mobile);

  // Return the updated order and new transaction
  res.json({
    message: "Payment updated successfully.",
    success: true,
    data: {
      updatedOrder,
      transaction: newTransaction,
    },
  });
});

export const updateFitOnRounds = asyncHandler(async (req, res) => {
  const { fitOnNumber, date, isChecked, salesOrderId } = req.body;

  if (!salesOrderId) {
    throw new Error("Order Id is required!");
  }
  const order = await SalesOrder.findOne({ salesOrderId })
    .populate("customer")
    .exec();

  // Check if the fitOnRound with the given fitOnNumber exists
  const existingFitOnRound = order.fitOnRounds.find(
    (round) => round.fitOnNumber === fitOnNumber
  );

  if (existingFitOnRound) {
    // If the fitOnNumber exists, update the date and isChecked
    existingFitOnRound.date = date || existingFitOnRound.date;
    existingFitOnRound.isChecked =
      isChecked !== undefined ? isChecked : existingFitOnRound.isChecked;
  } else {
    // If the fitOnNumber doesn't exist, add a new fitOnRound object
    order.fitOnRounds.push({
      fitOnNumber,
      date,
      isChecked,
    });
  }

  if (isChecked) {
    const fitOnDate = new Date(date).toISOString().split("T")[0];
    const smsBody = `Hi ${order.customer.name} your order ${salesOrderId} is ready for FitOn number ${fitOnNumber} on ${fitOnDate}.`;
    await sendSMS(smsBody, order.customer.mobile);
  }

  // Save the updated sales order
  const updatedOrder = await order.save();
  // Return the updated sales order
  res.json({
    message: "Fit On Rounds updated successfully.",
    success: true,
    data: updatedOrder,
  });
});
