import { Product } from "../models/productModel.js";

export const getDocId = async (Model, key, value) => {
  try {
    const doc = await Model.findOne({ [key]: value })
      .lean()
      .exec();
    return doc ? doc._id : null;
  } catch (error) {
    throw new Error(`Error retrieving document: ${error.message}`);
  }
};

export const getAutoGeneratedId = async (Model, idField, _id) => {
  try {
    const doc = await Model.findById(_id).lean().exec();
    return doc ? doc[idField] : null;
  } catch (error) {
    throw new Error(`Error retrieving document: ${error.message}`);
  }
};

export const getProductFields = async (_id) => {
  try {
    const product = await Product.findById(_id)
      .select("productId status type price")
      .lean()
      .exec();
    return product
      ? {
          productId: product.productId,
          status: product.status,
          type: product.type,
          price: product.price
        }
      : null;
  } catch (error) {
    throw new Error(`Error retrieving product: ${error.message}`);
  }
};
